name: "Release"

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Version"
        default: "0.0.0"

jobs:
  build:
    name: "Build Tagura"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout the Repository"
        uses: "actions/checkout@v4"

      - name: "Set up Zig"
        uses: "mlugg/setup-zig@v1"
        with:
          version: "0.14.0"

      - name: "Restore Zig Cache"
        uses: "actions/cache/restore@v4"
        with:
          path: ".zig-cache"
          key: "zig-cache"

      - name: "Build the Project"
        run: "zig build"

      - name: "Directory"
        run: "ls zig-out"

      - name: "Update Zig Cache"
        uses: "actions/cache/save@v4"
        with:
          path: ".zig-cache"
          key: "zig-cache"
      
      - name: "Upload the Artifacts"
        uses: 'actions/upload-artifact@v4'
        with:
          path: "zig-out"

  release:
    permissions: "write-all"
    needs: "build"

    name: "Create Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Create Release"
        uses: "actions/create-release@latest"
        with:
          prerelease: false
          draft: false
        
          tag_name: "v${{ github.event.inputs.version }}"
          release_name: "v${{ github.event.inputs.version }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
